name: Build tvOSBrowser

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show files
      run: |
        ls -la
        find . -name "*.xcodeproj"

    - name: Build
      run: |
        xcodebuild \
        -project xxx.xcodeproj \
        -scheme xxx \
        -sdk appletvos \
        -configuration Release \
        build
