name: Build tvOSBrowser

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        xcodebuild \
        -project _Project/Browser.xcodeproj \
        -scheme Browser \
        -sdk appletvos \
        -configuration Release \
        CODE_SIGNING_ALLOWED=NO \
        build

    - name: Package IPA
      run: |
        mkdir Payload
        cp -r ~/Library/Developer/Xcode/DerivedData/*/Build/Products/Release-appletvos/Browser.app Payload/
        zip -r Browser.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: tvOSBrowser-IPA
        path: Browser.ipa
